# Generated by Django 6.0.7 on 2026-08-28 12:37

from django.db import migrations, models


def backfill_description_from_address(apps, schema_editor):
    OrganizerProfile = apps.get_model("accounts", "OrganizerProfile")
    for profile in OrganizerProfile.objects.all():
        if not profile.description and profile.address:
            profile.description = profile.address
            profile.save(update_fields=["description"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profileeditrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(
            backfill_description_from_address,
            migrations.RunPython.noop,
        ),
    ]
