# Generated by Django 6.0.7 on 2026-08-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_participantrequest_participantresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booking_deadline',
            field=models.DateTimeField(blank=True, help_text='Last date/time to register. Leave blank for no deadline.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_available',
            field=models.BooleanField(default=False, help_text='Whether attendees can download a certificate of participation.'),
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_template',
            field=models.FileField(blank=True, help_text='Optional background template (image/PDF) used for certificates.', null=True, upload_to='certificate_templates/'),
        ),
        migrations.AddField(
            model_name='event',
            name='charging_stations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='food_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='food_details',
            field=models.CharField(blank=True, default='', help_text='Optional info about food and refreshments.', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.CharField(blank=True, default='', help_text="Language(s) the event is conducted in, e.g. 'English, Arabic'", max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='parking_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='parking_details',
            field=models.CharField(blank=True, default='', help_text='Optional notes about parking (e.g. free lot nearby, paid garage).', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='prayer_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='restrooms_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='water_refill_stations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='what_to_bring',
            field=models.TextField(blank=True, default='', help_text='Items participants should bring (e.g. student ID, laptop).'),
        ),
        migrations.AddField(
            model_name='event',
            name='wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='wifi_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='wifi_details',
            field=models.CharField(blank=True, default='', help_text='Optional Wi-Fi info (e.g. network name / password).', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('UPCOMING', 'Upcoming'), ('POSTPONED', 'Postponed'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
