# Generated by Django 6.0.7 on 2026-09-29 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventfavorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_data', models.JSONField(default=dict, help_text='Snapshot of the changed fields before the edit.')),
                ('proposed_data', models.JSONField(default=dict, help_text='New values submitted by the organizer (non file fields).')),
                ('changes', models.JSONField(default=list, help_text='Precomputed list of {field, label, old, new} entries for display.')),
                ('previous_status', models.CharField(default='UPCOMING', help_text='Event status to restore once the changes are approved.', max_length=20)),
                ('new_banner', models.ImageField(blank=True, null=True, upload_to='event_change_requests/')),
                ('new_certificate_template', models.FileField(blank=True, null=True, upload_to='certificate_change_requests/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='events.event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_event_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event change request',
                'verbose_name_plural': 'Event change requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='events_even_status_df2d70_idx'), models.Index(fields=['event', 'status'], name='events_even_event_i_324393_idx')],
            },
        ),
    ]
