# Generated by Django 6.0.7 on 2026-07-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_CONFIRMATION', 'Booking Confirmation'), ('BOOKING_REMINDER', 'Booking Reminder'), ('EVENT_UPDATE', 'Event Update'), ('ORGANIZER_APPROVAL', 'Organizer Approval'), ('ORGANIZER_REJECTED', 'Organizer Rejected'), ('EVENT_APPROVED', 'Event Approved'), ('EVENT_REJECTED', 'Event Rejected'), ('NEW_EXPERIENCE', 'New Experience'), ('CHAT_MESSAGE', 'Chat Message'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed')], max_length=50),
        ),
    ]
