# Generated by Django 6.0.7 on 2026-07-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_CONFIRMATION', 'Booking Confirmation'), ('BOOKING_REMINDER', 'Booking Reminder'), ('EVENT_UPDATE', 'Event Update'), ('ORGANIZER_APPROVAL', 'Organizer Approval'), ('ORGANIZER_REJECTED', 'Organizer Rejected'), ('EVENT_APPROVED', 'Event Approved'), ('EVENT_REJECTED', 'Event Rejected'), ('NEW_EXPERIENCE', 'New Experience'), ('CHAT_MESSAGE', 'Chat Message'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('PROFILE_EDIT_REQUEST', 'Profile Edit Request'), ('PROFILE_EDIT_APPROVED', 'Profile Edit Approved'), ('PROFILE_EDIT_REJECTED', 'Profile Edit Rejected'), ('EVENT_REQUEST_NEW', 'New Event Request'), ('EVENT_REQUEST_BID', 'New Bid on Event Request'), ('EVENT_REQUEST_BID_SELECTED', 'Bid Selected'), ('EVENT_REQUEST_COMMENT', 'Comment on Event Request'), ('EVENT_FEEDBACK_REMINDER', 'Feedback Reminder')], max_length=50),
        ),
    ]
