# Generated by Django 6.0.7 on 2026-08-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_CONFIRMATION', 'Booking Confirmation'), ('BOOKING_REMINDER', 'Booking Reminder'), ('EVENT_UPDATE', 'Event Update'), ('ORGANIZER_APPROVAL', 'Organizer Approval'), ('ORGANIZER_REJECTED', 'Organizer Rejected'), ('EVENT_APPROVED', 'Event Approved'), ('EVENT_REJECTED', 'Event Rejected'), ('NEW_EXPERIENCE', 'New Experience'), ('CHAT_MESSAGE', 'Chat Message'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('PROFILE_EDIT_REQUEST', 'Profile Edit Request'), ('PROFILE_EDIT_APPROVED', 'Profile Edit Approved'), ('PROFILE_EDIT_REJECTED', 'Profile Edit Rejected'), ('EVENT_FEEDBACK_REMINDER', 'Feedback Reminder'), ('FULLY_BOOKED', 'Event Fully Booked'), ('SEATS_AVAILABLE', 'Seats Became Available'), ('PARTICIPANT_REQUEST_NEW', 'New Participant Request'), ('PARTICIPANT_RESPONSE', 'New Participant Response'), ('EVENT_CANCELLED', 'Event Cancelled'), ('EVENT_POSTPONED', 'Event Postponed'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_REJECTED', 'Booking Rejected'), ('WAITLIST_JOINED', 'Joined Waitlist'), ('WAITLIST_ASSIGNED', 'Waitlist Assigned')], max_length=50),
        ),
    ]
