# Generated by Django 6.0.7 on 2026-09-30 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0005_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_CONFIRMATION', 'Booking Confirmation'), ('BOOKING_REMINDER', 'Booking Reminder'), ('EVENT_UPDATE', 'Event Update'), ('ORGANIZER_APPROVAL', 'Organizer Approval'), ('ORGANIZER_REJECTED', 'Organizer Rejected'), ('EVENT_APPROVED', 'Event Approved'), ('EVENT_REJECTED', 'Event Rejected'), ('NEW_EXPERIENCE', 'New Experience'), ('CHAT_MESSAGE', 'Chat Message'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('PROFILE_EDIT_REQUEST', 'Profile Edit Request'), ('PROFILE_EDIT_APPROVED', 'Profile Edit Approved'), ('PROFILE_EDIT_REJECTED', 'Profile Edit Rejected'), ('EVENT_FEEDBACK_REMINDER', 'Feedback Reminder'), ('FULLY_BOOKED', 'Event Fully Booked'), ('SEATS_AVAILABLE', 'Seats Became Available'), ('PARTICIPANT_REQUEST_NEW', 'New Participant Request'), ('PARTICIPANT_RESPONSE', 'New Participant Response'), ('EVENT_CANCELLED', 'Event Cancelled'), ('EVENT_POSTPONED', 'Event Postponed'), ('EVENT_CHANGE_REQUESTED', 'Event Change Requested'), ('EVENT_CHANGE_APPROVED', 'Event Change Approved'), ('EVENT_CHANGE_REJECTED', 'Event Change Rejected'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_REJECTED', 'Booking Rejected'), ('WAITLIST_JOINED', 'Joined Waitlist'), ('WAITLIST_ASSIGNED', 'Waitlist Assigned'), ('WELCOME', 'Welcome'), ('ORGANIZER_APPLICATION_RECEIVED', 'Organizer Application Received'), ('ACCOUNT_LOGIN', 'Account Login'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('PASSWORD_CHANGED', 'Password Changed'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('ACCOUNT_DEACTIVATED', 'Account Deactivated'), ('BOOKING_CANCELLED', 'Booking Cancelled')], max_length=50),
        ),
        migrations.CreateModel(
            name='EmailPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ACCOUNT', 'Account activity'), ('BOOKINGS', 'Bookings and tickets'), ('EVENTS', 'Event updates'), ('ORGANIZER', 'Organizer application updates'), ('MARKETING', 'Promotions and announcements')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
