# Generated by Django 6.0.7 on 2026-09-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0006_alter_notification_notification_type_emailpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='requires_action',
            field=models.BooleanField(default=False),
        ),
    ]
