from io import BytesIO

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

BRAND_ORANGE = HexColor("#E8622C")
BRAND_ORANGE_DARK = HexColor("#C94E1F")
BRAND_DARK = HexColor("#1A1A1A")
BRAND_MUTED = HexColor("#8C7E72")
BRAND_LIGHT_BG = HexColor("#F8F4F0")
BRAND_BORDER = HexColor("#E0D5CB")
BRAND_GREEN = HexColor("#2D8B4E")
BRAND_RED = HexColor("#C0392B")


def _row(c, x, y, w, h, fill=None):
    c.setFillColor(fill or HexColor("#FFFFFF"))
    c.rect(x, y, w, h, fill=1, stroke=0)


def _cell(c, x, y, w, h, text, font="Helvetica", size=8, color=BRAND_DARK, align="left"):
    c.setFont(font, size)
    c.setFillColor(color)
    if align == "center":
        c.drawCentredString(x + w / 2, y + (h - size * 1.2) / 2, str(text))
    else:
        c.drawString(x + 4, y + (h - size * 1.2) / 2, str(text))


def generate_participants_pdf(event, bookings):
    """Generate a participant list PDF for an event."""
    buffer = BytesIO()
    page_w, page_h = A4
    c = canvas.Canvas(buffer, pagesize=A4)
    margin = 16 * mm
    col_w = page_w - 2 * margin

    # ── header ──
    c.setFillColor(BRAND_ORANGE)
    c.rect(0, page_h - 30 * mm, page_w, 30 * mm, fill=1, stroke=0)
    c.setFillColor(HexColor("#FFFFFF"))
    c.setFont("Helvetica-Bold", 14)
    c.drawString(margin, page_h - 14 * mm, "EVENT")
    c.setFillColor(HexColor("#FFD4BB"))
    c.drawString(margin + 34, page_h - 14 * mm, "FINDER")
    c.setFillColor(HexColor("#FFFFFF"))
    c.setFont("Helvetica-Bold", 16)
    title = event.title
    if len(title) > 48:
        title = title[:46] + ".."
    c.drawString(margin, page_h - 24 * mm, title)

    # ── sub header ──
    y = page_h - 38 * mm
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(BRAND_DARK)
    c.drawString(margin, y, "Participant List")
    y -= 6 * mm
    c.setFont("Helvetica", 9)
    c.setFillColor(BRAND_MUTED)
    c.drawString(margin, y, f"Date: {event.start_date} - {event.end_date}    Venue: {event.venue}, {event.city}")
    c.drawString(margin, y - 4 * mm, f"Total bookings: {bookings.count()}    Confirmed: {bookings.filter(status='CONFIRMED').count()}")

    # ── table header ──
    y -= 14 * mm
    headers = [
        ("#", 0.06),
        ("NAME", 0.22),
        ("EMAIL", 0.26),
        ("PHONE", 0.18),
        ("TICKETS", 0.10),
        ("STATUS", 0.18),
    ]
    x = margin
    header_h = 7 * mm
    _row(c, x, y - header_h, col_w, header_h, BRAND_ORANGE)
    c.setFillColor(HexColor("#FFFFFF"))
    c.setFont("Helvetica-Bold", 8)
    hx = x
    for label, frac in headers:
        w = col_w * frac
        _cell(c, hx, y - header_h, w, header_h, label, font="Helvetica-Bold", size=8, color=HexColor("#FFFFFF"))
        hx += w

    y -= header_h
    row_h = 6.5 * mm
    line = 0
    for booking in bookings:
        if y - row_h < 15 * mm:
            c.showPage()
            y = page_h - 20 * mm
            hx = margin
            for label, frac in headers:
                w = col_w * frac
                _cell(c, hx, y - header_h, w, header_h, label, font="Helvetica-Bold", size=8, color=HexColor("#FFFFFF"))
                hx += w
            y -= header_h

        user = booking.user
        status = booking.status
        status_color = BRAND_GREEN if status == "CONFIRMED" else (BRAND_RED if status in ("CANCELLED", "REJECTED") else BRAND_ORANGE_DARK)
        row_fill = HexColor("#FDF8F4") if line % 2 else HexColor("#FFFFFF")
        _row(c, margin, y - row_h, col_w, row_h, row_fill)
        hx = margin
        for idx, (label, frac) in enumerate(headers):
            w = col_w * frac
            if idx == 0:
                text = line + 1
            elif idx == 1:
                text = user.get_full_name() or user.username
            elif idx == 2:
                text = user.email
            elif idx == 3:
                text = user.phone_number or "-"
            elif idx == 4:
                text = booking.number_of_tickets
            else:
                text = booking.status
            color = status_color if idx == 5 else BRAND_DARK
            _cell(c, hx, y - row_h, w, row_h, text, size=8, color=color)
            hx += w
        y -= row_h
        line += 1

    c.setFont("Helvetica", 7)
    c.setFillColor(BRAND_MUTED)
    c.drawString(margin, 12 * mm, "Generated by EventFinder")

    c.save()
    buffer.seek(0)
    return buffer
