# Generated by Django 6.0.7 on 2026-07-22 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_alter_event_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('preferred_location', models.CharField(max_length=255)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('expected_attendees', models.PositiveIntegerField(default=50)),
                ('budget_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_requirements', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RECEIVING_BIDS', 'Receiving Bids'), ('SELECTED', 'Organizer Selected'), ('CONVERTED', 'Converted to Event'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('demand_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('VIRAL', 'Viral')], default='LOW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_requests', to='events.category')),
                ('converted_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_plan', models.TextField(help_text='Detailed description of the event plan')),
                ('proposed_date', models.DateField()),
                ('proposed_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(max_length=255)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField()),
                ('budget_estimation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('benefits_included', models.TextField(help_text="What's included (certificates, food, mentors, etc.)")),
                ('additional_ideas', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_bids', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.eventrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.eventrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_request_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRequestSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='auctions.eventrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_request_supports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='eventrequest',
            index=models.Index(fields=['status', '-created_at'], name='auctions_ev_status_d94b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrequest',
            index=models.Index(fields=['category', 'status'], name='auctions_ev_categor_7104fd_idx'),
        ),
        migrations.AddIndex(
            model_name='eventbid',
            index=models.Index(fields=['request', 'status'], name='auctions_ev_request_ce0585_idx'),
        ),
        migrations.AddIndex(
            model_name='eventbid',
            index=models.Index(fields=['organizer', 'status'], name='auctions_ev_organiz_751cfa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventbid',
            unique_together={('request', 'organizer')},
        ),
        migrations.AddIndex(
            model_name='eventrequestcomment',
            index=models.Index(fields=['request', 'created_at'], name='auctions_ev_request_345aed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventrequestsupport',
            unique_together={('request', 'user')},
        ),
    ]
