# Generated by Django 6.0.7 on 2026-07-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequest',
            name='preferred_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
