# Generated by Django 6.0.7 on 2026-07-22 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_alter_event_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBlackBoxReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_attendees', models.PositiveIntegerField(default=0)),
                ('actual_attendees', models.PositiveIntegerField(default=0)),
                ('total_feedbacks', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('sentiment_positive', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of positive sentiment', max_digits=5)),
                ('sentiment_neutral', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sentiment_negative', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('success_factors', models.JSONField(blank=True, default=list, help_text='List of success factor strings')),
                ('problems_found', models.JSONField(blank=True, default=list, help_text='List of problem strings')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='List of recommendation strings')),
                ('category_stats', models.JSONField(blank=True, default=dict, help_text='Category-level statistics')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blackbox_report', to='events.event')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('positive_feedback', models.JSONField(blank=True, default=list, help_text='List of positive aspects: venue, speaker, activities, organization, networking')),
                ('problems', models.JSONField(blank=True, default=list, help_text='List of problems: late_start, poor_management, too_crowded, etc.')),
                ('suggestions', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'rating'], name='blackbox_ev_event_i_abb505_idx')],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
